### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by fugmulch** [Saibot393/enhancedcombathud-mutant-year-zero#1]
Attempted installation results in the following error:

[enhancedcombathud-mutant-year-zero] Metadata validation failed for module "enhancedcombathud-mutant-year-zero": The file "styles/MYZCustom.css" included by module enhancedcombathud-mutant-year-zero does not exist [setup.js:5105:19](http://129.213.87.30:30000/scripts/setup.js)
    #logPackageWarnings http://129.213.87.30:30000/scripts/setup.js:5105
    #setupView http://129.213.87.30:30000/scripts/setup.js:5072
    _initializeView http://129.213.87.30:30000/scripts/setup.js:5022
    initialize http://129.213.87.30:30000/scripts/foundry.js:8650

the module.json is looking for MYZCustom.css, but the file in the styles folder is myzCustom.css, is there dependency case sensitive?

**Comment by Saibot393** [comment]
The bug should be fixed with v1.1.1.
Out of interest, since the bug seems to only effect certain users, which browser and which OS are you using?

**Comment by fugmulch** [comment]
win 10, firefox, I am hosting on a oracle free cloud.
all fixed now however, thank you!

**Comment by Saibot393** [comment]
Good to hear.
The problem was a file being loaded with a name in all uppercase while actually being lowercase, windows accepts that, oracle (and probably other systems/providers) complain.
