### ISSUE TITLE
XP Advancement Questions are not working

### ISSUE THREAD

**Issue by bblonski** [Saibot393/enhancedcombathud-mutant-year-zero#3]
I'm trying to use the Trigger Character Advancement button on the toolbar to grant experience points, but that does not appear to work. I configured the experience options through the Configuration Settings menu, but nothing happens when I click the Trigger Character Advancement button. I don't see any errors in the console log either.

If I gant characters 5 XP, I see the Open Character Advancement Menu button in the combat hud, and this brings up the level up menu. But I can't get the menu to grant XP to come up.

Am I missing something, or is it broken right now?

**Comment by Saibot393** [comment]
Everything seems to work on my end, this is how it is intended to work:

1. The GM clicks the "Trigger character advancement" button on the top left
2. All currently logged in players are now able to open the xp gain menu via the arrow symbol in the portrait
![image](https://github.com/Saibot393/enhancedcombathud-mutant-year-zero/assets/137942782/c1d61be7-ab81-4aee-81c2-6609c0f0d711)
3. When the button is clicked the advancement menu opens for the player allowing them to answer the xp questions
![image](https://github.com/Saibot393/enhancedcombathud-mutant-year-zero/assets/137942782/6318b28d-e986-4033-8387-53c85a9d2ac0)
4. When the confirm button is pressed the players xp should be increased by the amount of questions answered with "yes"

**Comment by bblonski** [comment]
Ah yes. I didn't understand how it worked. I assumed that clicking the button would pop up a menu for the GM, or pop up the menu immediately for the PCs. I didn't notice the trigger advancement button on the portraits. Or I only noticed it after experimenting with adding experience and thought it was the same as the level up button.

I can confirm it works, but you might want to put some instructions in the readme.

**Comment by Saibot393** [comment]
Yeah, thats probably a good idea
